language: objective-c

osx_image: xcode8

before_install:
   - rvm install 2.2.2
   - sudo gem install bundler
   - sudo gem install cocoapods -v '1.1.1'
   - pod repo update

script:
   xcodebuild -workspace CoreDataServices.xcworkspace -scheme CoreDataServices test -destination 'platform=iOS Simulator,name=iPhone 6'
